### ISSUE TITLE
TEJO.org - ligiloj ĉe supra lingva menuo ne plu funkcias

### ISSUE THREAD

**Issue by konstanze-sj** [LaPingvino/tehxnike#1]
Ekde ŝanĝo de la traduka sistemo, la ligiloj de la menuo por selekti la lingvon de la retejo ne plu funkcias.

![lingva menuo](https://cloud.githubusercontent.com/assets/19655847/19176122/d987cf74-8c77-11e6-8cca-02fc6d9b2ed3.PNG)

**Comment by tejooficejo** [comment]
Verŝajne estas iu aŭtomataĵo kiu anstataŭigas lingvcelatajn ligilojn per lingvindentigĉeno de la lingvo enhavata en la kuketoj de la retejo (ekz. se la kuketo `qtrans_front_language` enhavas na `it` puŝante sur la butono por iri al la Angla versio, iu misteraĵo anstataŭigas na `tejo.org/en/` per `tejo.org/it`.
Mi provis ŝanĝi la celpunkton de butono por la lingva ŝanĝo ekz. el `tejo.org/fr` al `tejo.org/fri` kaj la ligilo povas bone funkcii (kompreneble la celpunkto ne ekzistas kaj konsekvence puŝante aperas eraron 404.).
Mi ne scias se eblas agordi tian misteraĵon por tion ne fari sed eble provizore oni povas ĉirkaŭeviti la misfunkciadon per ĉi solvo: oni povus krei plusendilojn ke sendu ekz. el `tejo.org/enlang/` al `tejo.org/en` kaj tiel fari por ĉiuj lingvoj. Poste oni povus ŝanĝi en la lingva menuo la celpunkton sufiksante per `lang`. Mi agnoskas ke estas iomete komplika solvo, sed eble povus provizore esti utila.

_Alessandro_

**Comment by konstanze-sj** [comment]
Mi poras la proponon. Antaŭe, eble, oni povus provi forigi la menuon entute
kaj refari saman. Alessandro, bonvolu rigardi unue ĉe la agordoj de la nova
kromprogrameto por traduki (mi ĉiam forgesas la nomon), tie estas informoj
por elekto inter /xx, ?lang=xx kaj aliaj agordebloj.

2016-10-07 20:10 GMT+09:00 tejooficejo notifications@github.com:

**Comment by LaPingvino** [comment]
mi rigardis tra la dokumentoj de qTranslate-x kaj tie oni menciis ke necesas uzi #?lang=lingvokodo, tion mi faris kaj nun funkcias.
